CREATE TABLE tb_proprietario (
    id BIGINT NOT NULL AUTO_INCREMENT,

    nome VARCHAR(255) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    telefone VARCHAR(20) NOT NULL ,
    situacao ENUM('ATIVO', 'INATIVO') NOT NULL,

    PRIMARY KEY (id)
);